config/routes.rb
SampleApp1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
	validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
  validates :password, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Welcome!"
      redirect_to @user
  	else
      render 'new'
  	end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-static-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          %li= link_to "Sign In", "#"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js", :type => "javascript"}    
    
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        .alert{:class => "alert-#{key}"}
          = value
      = yield
      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains 
      = pluralize @user.errors.count, "error"
      \.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/static_pages/about.html.haml
- provide(:title,"About Us")
%h1 About
%p Find me in app/views/static_pages/about.html.erb

app/views/static_pages/contact.html.haml
- provide(:title,'Contact')
%h1 Contact Us
%p Find me in app/views/static_pages/contact.html.erb

app/views/static_pages/help.html.haml
- provide(:title,"Help")
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.erb

app/views/static_pages/home.html.haml
- provide :title, "Home"
.center.hero-unit
	%h1 Welcome to the Sample App
	%h2 
		This is the home page for the
		%a{:href=>"http://railstutorial.org/"} Ruby on Rails Tutorial
		sample application.
	= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/new.html.haml
- provide :title, 'Sign up'
%h1 Sign up
.row
	.span6.offset3
		= form_for(@user) do |f|
			= render 'shared/error_messages'
			= f.label :name
			= f.text_field :name
			= f.label :email
			= f.text_field :email
			= f.label :password
			= f.password_field :password
			= f.label :password_confirmation, "Confirmation"
			= f.password_field :password_confirmation
			= f.submit "Create my account", class: "btn btn-large btn-primary"
		

app/views/users/show.html.haml
- provide :title, @user.name
%h1= @user.name
%p=	@user.email